In [1]:
# HYPERPARAMETER:
#1. TRAINING SET(COURSE SET)
#2. VALIDATION SET(PRACTICE EXAM)
#3. TEST SET(FINAL EXAM)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
Data=pd.read_csv('Heart_Disease.csv')

In [4]:
Data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [5]:
from sklearn.ensemble import RandomForestClassifier

In [6]:
RFC=RandomForestClassifier()

In [7]:
RFC.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [8]:
# THE MAIN PARAMETERS USED BY A RANDOM FOREST CLASSIFIER ARE:
# criterion = THE FUNCTION USED TO EVALUATE THE QUALITY OF SPLIT
# max_depth = MAXIMUM NUMBER OF LEVELS ALLOWED IN EACH TREE
# max_features = MAXIMUM NUMBER OF FEATURES CONSIDERED WHEN SPLITTING A NODE
# min_samples_leaf = MINIMUM NUMBER OF SAMPLES THAT CAN BE STORED IN A TREE LEAF
# min_samples_split = MINIMUM NUMBER OF SAMPLES NECESSARY IN A NODE TO CAUSE NODE SPLITTING
# n_estimators = NUMBER OF TREES IN AN ENSEMBLE

In [9]:
# MANUAL HYPERPARAMETER TUNING

In [10]:
# DATA SHUFFLING:
Data1=Data.sample(frac=1)
Data1

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
176   60    1   0       117   230    1        1      160      1      1.4   
217   63    1   0       130   330    1        0      132      1      1.8   
73    51    1   0       140   261    0        0      186      1      0.0   
161   55    0   1       132   342    0        1      166      0      1.2   
155   58    0   0       130   197    0        1      131      0      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
87    46    1   1       101   197    1        1      156      0      0.0   
283   40    1   0       152   223    0        1      181      0      0.0   
95    53    1   0       142   226    0        0      111      1      0.0   
98    43    1   2       130   315    0        1      162      0      1.9   
20    59    1   0       135   234    0        1      161      0      0.5   

     slope  ca  thal  target  
176      2   2     3       0  
217      2   3     3       0  
73       2   0     2       1  
161      2   0     2       1  
155      1   0     2       1  
..     ...  ..   ...     ...  
87       2   0     3       1  
283      2   0     3       0  
95       2   0     3       1  
98       2   1     2       1  
20       1   0     3       1  

[303 rows x 14 columns]

In [11]:
Data

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [12]:
x=Data1.drop('target',axis=1)
y=Data1['target']

In [13]:
Train_Split=round(0.7*len(Data1))
Train_Split

212

In [14]:
Validation_Split=round(Train_Split+0.15*len(Data1))
Validation_Split

257

In [15]:
X_Train,Y_Train=x[:Train_Split],y[:Train_Split]

In [16]:
X_Train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
176   60    1   0       117   230    1        1      160      1      1.4   
217   63    1   0       130   330    1        0      132      1      1.8   
73    51    1   0       140   261    0        0      186      1      0.0   
161   55    0   1       132   342    0        1      166      0      1.2   
155   58    0   0       130   197    0        1      131      0      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
219   48    1   0       130   256    1        0      150      1      0.0   
42    45    1   0       104   208    0        0      148      1      3.0   
19    69    0   3       140   239    0        1      151      0      1.8   
292   58    0   0       170   225    1        0      146      1      2.8   
224   54    1   0       110   239    0        1      126      1      2.8   

     slope  ca  thal  
176      2   2     3  
217      2   3     3  
73       2   0     2  
161      2   0     2  
155      1   0     2  
..     ...  ..   ...  
219      2   2     3  
42       1   0     2  
19       2   2     2  
292      1   2     1  
224      1   1     3  

[212 rows x 13 columns]

In [17]:
X_Train.tail(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
219   48    1   0       130   256    1        0      150      1      0.0   
42    45    1   0       104   208    0        0      148      1      3.0   
19    69    0   3       140   239    0        1      151      0      1.8   
292   58    0   0       170   225    1        0      146      1      2.8   
224   54    1   0       110   239    0        1      126      1      2.8   

     slope  ca  thal  
219      2   2     3  
42       1   0     2  
19       2   2     2  
292      1   2     1  
224      1   1     3

In [18]:
len(X_Train)

212

In [19]:
np.array(Y_Train)

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0], dtype=int64)

In [20]:
X_Valid,Y_Valid=x[Train_Split:Validation_Split],y[Train_Split:Validation_Split]

In [21]:
X_Valid

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
142   42    0   2       120   209    0        1      173      0      0.0   
169   53    1   0       140   203    1        0      155      1      3.1   
276   58    1   0       146   218    0        1      105      0      2.0   
138   57    1   0       110   201    0        1      126      1      1.5   
171   48    1   1       110   229    0        1      168      0      1.0   
78    52    1   1       128   205    1        1      184      0      0.0   
265   66    1   0       112   212    0        0      132      1      0.1   
216   62    0   2       130   263    0        1       97      0      1.2   
257   50    1   0       144   200    0        0      126      1      0.9   
194   60    1   2       140   185    0        0      155      0      3.0   
188   50    1   2       140   233    0        1      163      0      0.6   
34    51    1   3       125   213    0        0      125      1      1.4   
130   54    0   2       160   201    0        1      163      0      0.0   
48    53    0   2       128   216    0        0      115      0      0.0   
281   52    1   0       128   204    1        1      156      1      1.0   
266   55    0   0       180   327    0        2      117      1      3.4   
167   62    0   0       140   268    0        0      160      0      3.6   
238   77    1   0       125   304    0        0      162      1      0.0   
65    35    0   0       138   183    0        1      182      0      1.4   
153   66    0   2       146   278    0        0      152      0      0.0   
45    52    1   1       120   325    0        1      172      0      0.2   
84    42    0   0       102   265    0        0      122      0      0.6   
160   56    1   1       120   240    0        1      169      0      0.0   
82    60    0   2       102   318    0        1      160      0      0.0   
32    44    1   1       130   219    0        0      188      0      0.0   
245   48    1   0       124   274    0        0      166      0      0.5   
195   59    1   0       170   326    0        0      140      1      3.4   
212   39    1   0       118   219    0        1      140      0      1.2   
158   58    1   1       125   220    0        1      144      0      0.4   
261   52    1   0       112   230    0        1      160      0      0.0   
164   38    1   2       138   175    0        1      173      0      0.0   
170   56    1   2       130   256    1        0      142      1      0.6   
203   68    1   2       180   274    1        0      150      1      1.6   
52    62    1   2       130   231    0        1      146      0      1.8   
174   60    1   0       130   206    0        0      132      1      2.4   
232   55    1   0       160   289    0        0      145      1      0.8   
132   42    1   1       120   295    0        1      162      0      0.0   
44    39    1   2       140   321    0        0      182      0      0.0   
70    54    1   2       120   258    0        0      147      0      0.4   
192   54    1   0       120   188    0        1      113      0      1.4   
128   52    0   2       136   196    0        0      169      0      0.1   
201   60    1   0       125   258    0        0      141      1      2.8   
125   34    0   1       118   210    0        1      192      0      0.7   
93    54    0   1       132   288    1        0      159      1      0.0   
286   59    1   3       134   204    0        1      162      0      0.8   

     slope  ca  thal  
142      1   0     2  
169      0   0     3  
276      1   1     3  
138      1   0     1  
171      0   0     3  
78       2   0     2  
265      2   1     2  
216      1   1     3  
257      1   0     3  
194      1   0     2  
188      1   1     3  
34       2   1     2  
130      2   1     2  
48       2   0     0  
281      1   0     0  
266      1   0     2  
167      0   2     2  
238      2   3     2  
65       2   0     2  
153      1   1     2  
45       2   0     2  
84

In [22]:
len(X_Valid)

45

In [23]:
np.array(Y_Valid)

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0], dtype=int64)

In [24]:
X_Test,Y_Test=x[Validation_Split:],y[Validation_Split:]

In [25]:
X_Test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
235   51    1   0       140   299    0        1      173      1      1.6   
258   62    0   0       150   244    0        1      154      1      1.4   
209   59    1   0       140   177    0        1      162      1      0.0   
152   64    1   3       170   227    0        0      155      0      0.6   
259   38    1   3       120   231    0        1      182      1      3.8   
133   41    1   1       110   235    0        1      153      0      0.0   
210   57    1   2       128   229    0        0      150      0      0.4   
61    54    1   1       108   309    0        1      156      0      0.0   
31    65    1   0       120   177    0        1      140      0      0.4   
157   35    1   1       122   192    0        1      174      0      0.0   
208   49    1   2       120   188    0        1      139      0      2.0   
274   47    1   0       110   275    0        0      118      1      1.0   
196   46    1   2       150   231    0        1      147      0      3.6   
63    41    1   1       135   203    0        1      132      0      0.0   
244   56    1   0       132   184    0        0      105      1      2.1   
77    59    1   1       140   221    0        1      164      1      0.0   
162   41    1   1       120   157    0        1      182      0      0.0   
140   51    0   2       120   295    0        0      157      0      0.6   
111   57    1   2       150   126    1        1      173      0      0.2   
69    62    0   0       124   209    0        1      163      0      0.0   
297   59    1   0       164   176    1        0       90      0      1.0   
185   44    1   0       112   290    0        0      153      0      0.0   
263   63    0   0       108   269    0        1      169      1      1.8   
33    54    1   2       125   273    0        0      152      0      0.5   
294   44    1   0       120   169    0        1      144      1      2.8   
72    29    1   1       130   204    0        0      202      0      0.0   
9     57    1   2       150   168    0        1      174      0      1.6   
239   35    1   0       126   282    0        0      156      1      0.0   
106   69    1   3       160   234    1        0      131      0      0.1   
5     57    1   0       140   192    0        1      148      0      0.4   
178   43    1   0       120   177    0        0      120      1      2.5   
253   67    1   0       100   299    0        0      125      1      0.9   
225   70    1   0       145   174    0        1      125      1      2.6   
17    66    0   3       150   226    0        1      114      0      2.6   
287   57    1   1       154   232    0        0      164      0      0.0   
117   56    1   3       120   193    0        0      162      0      1.9   
148   44    1   2       120   226    0        1      169      0      0.0   
264   54    1   0       110   206    0        0      108      1      0.0   
135   49    0   0       130   269    0        1      163      0      0.0   
54    63    0   2       135   252    0        0      172      0      0.0   
59    57    0   0       128   303    0        0      159      0      0.0   
87    46    1   1       101   197    1        1      156      0      0.0   
283   40    1   0       152   223    0        1      181      0      0.0   
95    53    1   0       142   226    0        0      111      1      0.0   
98    43    1   2       130   315    0        1      162      0      1.9   
20    59    1   0       135   234    0        1      161      0      0.5   

     slope  ca  thal  
235      2   0     3  
258      1   0     2  
209      2   1     3  
152      1   0     3  
259      1   0     3  
133      2   0     2  
210      1   1     3  
61       2   0     3  
31       2   0     3  
157      2   0     2  
208      1   3     3  
274      1   1     2  
196      1   0     2  
63       1   0     1  
244      1   1     1  
77       2   0     2  
162      2   0     2  
140      2   0    

In [26]:
len(X_Test)

46

In [27]:
np.array(Y_Test)

array([0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1], dtype=int64)

In [28]:
len(X_Train),len(X_Valid),len(X_Test)

(212, 45, 46)

In [29]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,precision_score,recall_score,f1_score

In [30]:
def Evaluate_Pred(Y_Actual,Y_Pred):
    Accuracy=accuracy_score(Y_Actual,Y_Pred)
    Precision_Score=precision_score(Y_Actual,Y_Pred)
    Recall_Score=recall_score(Y_Actual,Y_Pred)
    F1_Score=f1_score(Y_Actual,Y_Pred)
    print(f'Confusion Matrix:\n{confusion_matrix(Y_Actual,Y_Pred)}')
    print(f'Accuracy Score:{Accuracy*100:.2f}%')
    print(f'Classificatio Report:\n{classification_report(Y_Actual,Y_Pred)}')
    print(f'Presion Score:{Precision_Score:.2f}')
    print(f'Recall Score:{Recall_Score:.2f}')
    print(f'F1 Score:{F1_Score:.2f}')

In [31]:
RFC.fit(X_Train,Y_Train)
Y_Pred=RFC.predict(X_Valid)

In [32]:
Y_Pred

array([1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1], dtype=int64)

In [33]:
Evaluation1=Evaluate_Pred(Y_Valid,Y_Pred)

Confusion Matrix:
[[17  6]
 [ 4 18]]
Accuracy Score:77.78%
Classificatio Report:
              precision    recall  f1-score   support

           0       0.81      0.74      0.77        23
           1       0.75      0.82      0.78        22

    accuracy                           0.78        45
   macro avg       0.78      0.78      0.78        45
weighted avg       0.78      0.78      0.78        45

Presion Score:0.75
Recall Score:0.82
F1 Score:0.78


In [34]:
RFC1=RandomForestClassifier(n_estimators=85)
RFC1.fit(X_Train,Y_Train)
Y_Pred1=RFC1.predict(X_Valid)

In [35]:
Y_Pred1

array([1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1], dtype=int64)

In [36]:
Evaluation2=Evaluate_Pred(Y_Valid,Y_Pred1)

Confusion Matrix:
[[16  7]
 [ 3 19]]
Accuracy Score:77.78%
Classificatio Report:
              precision    recall  f1-score   support

           0       0.84      0.70      0.76        23
           1       0.73      0.86      0.79        22

    accuracy                           0.78        45
   macro avg       0.79      0.78      0.78        45
weighted avg       0.79      0.78      0.78        45

Presion Score:0.73
Recall Score:0.86
F1 Score:0.79


In [37]:
# RANDOMIZED SEARCH CV:
from sklearn.model_selection import RandomizedSearchCV

In [38]:
Grid={'n_estimators':[10,100,200,500,1000,1200],
      'max_depth':[None,5,10,20,30],
      'max_features':['auto','sqrt'],
      'min_samples_split':[2,4,6],
      'min_samples_leaf':[1,2,4]}

In [39]:
(6*5*2*3*3)*5

2700

In [40]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [41]:
RFC2=RandomForestClassifier(n_jobs=1)
RSC=RandomizedSearchCV(estimator=RFC2,param_distributions=Grid,n_iter=10,cv=5,verbose=2)
# ALL ARE SELECTED RANDOMLY(CV=5,N-ITER=10--->5*10=50FITS) (10 RANDOMLY CHOOSEN USING 5 PARAMETERS IN GRID)

In [42]:
RSC.fit(x_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV] n_estimators=500, min_samples_split=2, min_samples_leaf=2, max_features=auto, max_depth=10 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  n_estimators=500, min_samples_split=2, min_samples_leaf=2, max_features=auto, max_depth=10, total=   0.7s
[CV] n_estimators=500, min_samples_split=2, min_samples_leaf=2, max_features=auto, max_depth=10 


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.7s remaining:    0.0s


[CV]  n_estimators=500, min_samples_split=2, min_samples_leaf=2, max_features=auto, max_depth=10, total=   0.9s
[CV] n_estimators=500, min_samples_split=2, min_samples_leaf=2, max_features=auto, max_depth=10 
[CV]  n_estimators=500, min_samples_split=2, min_samples_leaf=2, max_features=auto, max_depth=10, total=   0.7s
[CV] n_estimators=500, min_samples_split=2, min_samples_leaf=2, max_features=auto, max_depth=10 
[CV]  n_estimators=500, min_samples_split=2, min_samples_leaf=2, max_features=auto, max_depth=10, total=   0.7s
[CV] n_estimators=500, min_samples_split=2, min_samples_leaf=2, max_features=auto, max_depth=10 
[CV]  n_estimators=500, min_samples_split=2, min_samples_leaf=2, max_features=auto, max_depth=10, total=   0.7s
[CV] n_estimators=100, min_samples_split=4, min_samples_leaf=1, max_features=auto, max_depth=5 
[CV]  n_estimators=100, min_samples_split=4, min_samples_leaf=1, max_features=auto, max_depth=5, total=   0.2s
[CV] n_estimators=100, min_samples_split=4, min_sample

[CV]  n_estimators=1000, min_samples_split=2, min_samples_leaf=2, max_features=auto, max_depth=20, total=   1.4s
[CV] n_estimators=1000, min_samples_split=2, min_samples_leaf=2, max_features=auto, max_depth=20 
[CV]  n_estimators=1000, min_samples_split=2, min_samples_leaf=2, max_features=auto, max_depth=20, total=   1.3s
[CV] n_estimators=1000, min_samples_split=2, min_samples_leaf=2, max_features=auto, max_depth=20 
[CV]  n_estimators=1000, min_samples_split=2, min_samples_leaf=2, max_features=auto, max_depth=20, total=   1.4s
[CV] n_estimators=1000, min_samples_split=2, min_samples_leaf=2, max_features=auto, max_depth=20 
[CV]  n_estimators=1000, min_samples_split=2, min_samples_leaf=2, max_features=auto, max_depth=20, total=   1.3s
[CV] n_estimators=100, min_samples_split=6, min_samples_leaf=2, max_features=sqrt, max_depth=20 
[CV]  n_estimators=100, min_samples_split=6, min_samples_leaf=2, max_features=sqrt, max_depth=20, total=   0.1s
[CV] n_estimators=100, min_samples_split=6, m

[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:   42.3s finished


RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(n_jobs=1),
                   param_distributions={'max_depth': [None, 5, 10, 20, 30],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 4, 6],
                                        'n_estimators': [10, 100, 200, 500,
                                                         1000, 1200]},
                   verbose=2)

In [43]:
RSC.best_params_

{'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 30}

In [44]:
y_pred=RSC.predict(x_test)

In [45]:
y_pred

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1], dtype=int64)

In [46]:
Evaluation3=Evaluate_Pred(y_test,y_pred)

Confusion Matrix:
[[21  5]
 [ 7 28]]
Accuracy Score:80.33%
Classificatio Report:
              precision    recall  f1-score   support

           0       0.75      0.81      0.78        26
           1       0.85      0.80      0.82        35

    accuracy                           0.80        61
   macro avg       0.80      0.80      0.80        61
weighted avg       0.81      0.80      0.80        61

Presion Score:0.85
Recall Score:0.80
F1 Score:0.82


In [47]:
# GRID SEARCH CV:
Grid1={'n_estimators':[100,200,500],
      'max_depth':[None],
      'max_features':['auto','sqrt'],
      'min_samples_split':[6],
      'min_samples_leaf':[1,2]}

In [48]:
from sklearn.model_selection import GridSearchCV

In [49]:
RFC3=RandomForestClassifier(n_jobs=1)
GSC=GridSearchCV(estimator=RFC3,param_grid=Grid1,cv=5,verbose=2)

In [50]:
GSC.fit(x_train,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV] max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=6, n_estimators=100 
[CV]  max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=6, n_estimators=100, total=   0.2s
[CV] max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=6, n_estimators=100 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s


[CV]  max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=6, n_estimators=100, total=   0.1s
[CV] max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=6, n_estimators=100 
[CV]  max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=6, n_estimators=100, total=   0.2s
[CV] max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=6, n_estimators=100 
[CV]  max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=6, n_estimators=100, total=   0.2s
[CV] max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=6, n_estimators=100 
[CV]  max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=6, n_estimators=100, total=   0.2s
[CV] max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=6, n_estimators=200 
[CV]  max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=6, n_estimators=200, total=   0.3s
[CV] max_depth=None, max_features=

[CV]  max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=6, n_estimators=500, total=   0.8s
[CV] max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=6, n_estimators=500 
[CV]  max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=6, n_estimators=500, total=   0.7s
[CV] max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=6, n_estimators=500 
[CV]  max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=6, n_estimators=500, total=   0.6s
[CV] max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=6, n_estimators=500 
[CV]  max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=6, n_estimators=500, total=   0.7s
[CV] max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=6, n_estimators=500 
[CV]  max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=6, n_estimators=500, total=   0.7s
[CV] max_depth=None, max_features=

[Parallel(n_jobs=1)]: Done  60 out of  60 | elapsed:   23.3s finished


GridSearchCV(cv=5, estimator=RandomForestClassifier(n_jobs=1),
             param_grid={'max_depth': [None], 'max_features': ['auto', 'sqrt'],
                         'min_samples_leaf': [1, 2], 'min_samples_split': [6],
                         'n_estimators': [100, 200, 500]},
             verbose=2)

In [51]:
GSC.best_params_

{'max_depth': None,
 'max_features': 'auto',
 'min_samples_leaf': 1,
 'min_samples_split': 6,
 'n_estimators': 100}

In [52]:
y_pred1=GSC.predict(x_test)
y_pred1

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1], dtype=int64)

In [53]:
Evaluation4=Evaluate_Pred(y_test,y_pred1)

Confusion Matrix:
[[22  4]
 [ 6 29]]
Accuracy Score:83.61%
Classificatio Report:
              precision    recall  f1-score   support

           0       0.79      0.85      0.81        26
           1       0.88      0.83      0.85        35

    accuracy                           0.84        61
   macro avg       0.83      0.84      0.83        61
weighted avg       0.84      0.84      0.84        61

Presion Score:0.88
Recall Score:0.83
F1 Score:0.85


In [54]:
# SAVING THE MODEL
#1. USING PICKLE MODULE
#2  USING JOBLIB MODULE

In [55]:
#1 PICKLE MODULE
import pickle

In [56]:
# SAVE THE MODEL
pickle.dump(RSC,open('Randomized Search CV.pkl','wb'))

In [57]:
# LOAD THE MODEL
Loaded_Model=pickle.load(open('Randomized Search CV.pkl','rb'))

In [58]:
Loaded_Model

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(n_jobs=1),
                   param_distributions={'max_depth': [None, 5, 10, 20, 30],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 4, 6],
                                        'n_estimators': [10, 100, 200, 500,
                                                         1000, 1200]},
                   verbose=2)

In [59]:
Pickle_Y_Pred=Loaded_Model.predict(x_test)

In [60]:
Pickle_Y_Pred

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1], dtype=int64)

In [61]:
Evaluate_Pred(y_test,Pickle_Y_Pred)

Confusion Matrix:
[[21  5]
 [ 7 28]]
Accuracy Score:80.33%
Classificatio Report:
              precision    recall  f1-score   support

           0       0.75      0.81      0.78        26
           1       0.85      0.80      0.82        35

    accuracy                           0.80        61
   macro avg       0.80      0.80      0.80        61
weighted avg       0.81      0.80      0.80        61

Presion Score:0.85
Recall Score:0.80
F1 Score:0.82


In [62]:
#2 JOBLIB MODULE
from joblib import dump,load

In [63]:
# SAVE THE MODEL
dump(GSC,filename='Grid Search CV.joblib')

['Grid Search CV.joblib']

In [64]:
# LOAD THE MODEL
Loaded_Joblib_Model=load(filename='Grid Search CV.joblib')

In [65]:
Loaded_Joblib_Model

GridSearchCV(cv=5, estimator=RandomForestClassifier(n_jobs=1),
             param_grid={'max_depth': [None], 'max_features': ['auto', 'sqrt'],
                         'min_samples_leaf': [1, 2], 'min_samples_split': [6],
                         'n_estimators': [100, 200, 500]},
             verbose=2)

In [66]:
Joblib_Y_Pred=Loaded_Joblib_Model.predict(x_test)

In [67]:
Joblib_Y_Pred

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1], dtype=int64)

In [68]:
Evaluate_Pred(y_test,Joblib_Y_Pred)

Confusion Matrix:
[[22  4]
 [ 6 29]]
Accuracy Score:83.61%
Classificatio Report:
              precision    recall  f1-score   support

           0       0.79      0.85      0.81        26
           1       0.88      0.83      0.85        35

    accuracy                           0.84        61
   macro avg       0.83      0.84      0.83        61
weighted avg       0.84      0.84      0.84        61

Presion Score:0.88
Recall Score:0.83
F1 Score:0.85
