In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# lABEL ENCODER: DATA IN ORDER(ORDINAL DATA)
# ONEHOT ENCODER: DATA ARE NOT IN ANY ORDER(NOMINAL DATA)

In [3]:
Data=pd.read_csv('Car_Sales_Extended.csv')

In [4]:
Data.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [5]:
Data['Doors'].value_counts()

4    856
5     79
3     65
Name: Doors, dtype: int64

In [6]:
Data['Doors'].unique()

array([4, 5, 3], dtype=int64)

In [7]:
Data['Price'].value_counts().sort_values(ascending=False)

28414    2
7994     2
13560    2
17520    2
4566     2
        ..
20450    1
4034     1
16320    1
16319    1
16732    1
Name: Price, Length: 984, dtype: int64

In [8]:
Colours=[Data['Colour'].value_counts().sort_values(ascending=False).index]
Colours

[Index(['White', 'Blue', 'Black', 'Red', 'Green'], dtype='object')]

In [9]:
for col in Data.columns:
    print(col,':',len(Data[col].unique()),'Labels')

Make : 4 Labels
Colour : 5 Labels
Odometer (KM) : 998 Labels
Doors : 3 Labels
Price : 984 Labels


In [10]:
pd.get_dummies(Data[['Make','Colour','Doors']]).shape

(1000, 10)

In [11]:
pd.get_dummies(Data[['Make','Colour','Doors']],drop_first=True)

Doors  Make_Honda  Make_Nissan  Make_Toyota  Colour_Blue  Colour_Green  \
0        4           1            0            0            0             0   
1        5           0            0            0            1             0   
2        4           1            0            0            0             0   
3        4           0            0            1            0             0   
4        3           0            1            0            1             0   
..     ...         ...          ...          ...          ...           ...   
995      4           0            0            1            0             0   
996      3           0            1            0            0             0   
997      4           0            1            0            1             0   
998      4           1            0            0            0             0   
999      4           0            0            1            1             0   

     Colour_Red  Colour_White  
0             0             1  
1             0             0  
2             0             1  
3             0             1  
4             0             0  
..          ...           ...  
995           0             0  
996           0             1  
997           0             0  
998           0             1  
999           0             0  

[1000 rows x 8 columns]

In [12]:
len(Data)

1000

In [13]:
Data.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [14]:
x=Data.drop('Price',axis=1)
y=Data['Price']

In [15]:
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
COLOUR=LE.fit_transform(Data['Colour'])
COLOUR

array([4, 1, 4, 4, 1, 3, 1, 4, 4, 1, 4, 2, 4, 4, 1, 1, 3, 4, 4, 1, 1, 1,
       4, 2, 1, 1, 4, 2, 4, 4, 1, 4, 4, 2, 1, 1, 1, 4, 1, 2, 4, 1, 0, 1,
       1, 1, 4, 1, 4, 0, 3, 4, 1, 1, 4, 4, 4, 3, 3, 1, 3, 0, 2, 2, 4, 4,
       1, 0, 1, 4, 4, 2, 4, 3, 1, 1, 1, 4, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1,
       3, 1, 4, 4, 4, 4, 2, 1, 1, 0, 3, 1, 1, 4, 4, 4, 4, 1, 4, 4, 1, 1,
       4, 4, 4, 1, 4, 0, 0, 4, 1, 4, 4, 1, 1, 4, 0, 1, 4, 3, 4, 4, 1, 3,
       4, 2, 4, 1, 4, 1, 3, 1, 1, 4, 4, 1, 1, 4, 4, 1, 4, 2, 4, 3, 4, 2,
       4, 4, 4, 0, 2, 4, 4, 1, 4, 1, 4, 1, 1, 1, 1, 1, 1, 4, 1, 0, 4, 1,
       1, 1, 4, 0, 3, 4, 1, 4, 2, 3, 0, 1, 4, 1, 2, 1, 4, 0, 4, 2, 1, 2,
       4, 1, 4, 3, 1, 1, 3, 1, 4, 0, 1, 4, 0, 4, 4, 2, 2, 4, 1, 4, 1, 2,
       4, 1, 4, 4, 1, 2, 4, 1, 3, 3, 4, 3, 1, 1, 4, 2, 1, 1, 4, 0, 1, 4,
       4, 2, 3, 1, 4, 4, 1, 3, 4, 0, 1, 0, 1, 1, 1, 3, 3, 3, 4, 4, 2, 4,
       4, 4, 0, 1, 4, 2, 1, 4, 4, 1, 4, 1, 4, 1, 1, 4, 4, 1, 4, 1, 3, 2,
       4, 4, 2, 4, 0, 3, 3, 4, 4, 4, 4, 3, 1, 0, 4,

In [16]:
Z=pd.DataFrame(data=COLOUR,columns=['COLOUR'])

In [17]:
Z.head(25)

COLOUR
0        4
1        1
2        4
3        4
4        1
5        3
6        1
7        4
8        4
9        1
10       4
11       2
12       4
13       4
14       1
15       1
16       3
17       4
18       4
19       1
20       1
21       1
22       4
23       2
24       1

In [18]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [19]:
t=[['Make','Colour','Doors']]

In [20]:
# COLUMN TRANSFORMER TAKES THE ONEHOTENCODER AND APPLY TO THE CATEGORICAL FEATURES AND THE REMAINDER OF THE COLUMN TO PASSTHROUGH(DO NOT MAKE CHANGES)
Categorical_Features=['Make','Colour','Doors']
OHE=OneHotEncoder()
CT=ColumnTransformer([('One_Hot',OHE,Categorical_Features)],remainder='passthrough')

In [21]:
x_Transformed=CT.fit_transform(x)

In [22]:
x_Transformed

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [23]:
pd.DataFrame(x_Transformed)

0    1    2    3    4    5    6    7    8    9   10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_Transformed,y,test_size=0.2,random_state=42)

In [25]:
from sklearn.ensemble import RandomForestClassifier

In [26]:
RFC=RandomForestClassifier()

In [27]:
RFC.fit(x_train,y_train)

RandomForestClassifier()