In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_boston
Boston=load_boston()

In [3]:
Boston;

In [4]:
Data=pd.DataFrame(Boston['data'],columns=Boston['feature_names'])
Data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [5]:
Data['Target']=pd.Series(Boston['target'])

In [6]:
Data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  Target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  394.63   2.94    33.4  
4       18.7  396.90   5.33    36.2  
..       ...     ...    ...     ...  
501     21.0  391.99   9.67    22.4  
502     21.0  396.90   9.08    20.6  
503     21.0  396.90   5.64    23.9  
504     21.0  393.45   6.48    22.0  
505     21.0  396.90   7.88    11.9  

[506 rows x 14 columns]

In [7]:
x=Data.drop('Target',axis=1)
y=Data['Target']

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [9]:
from sklearn.ensemble import RandomForestRegressor

In [10]:
RFR=RandomForestRegressor()

In [11]:
RFR.fit(x_train,y_train)

RandomForestRegressor()

In [12]:
y_pred=RFR.predict(x_test)
y_pred

array([22.501, 30.298, 17.008, 23.048, 17.037, 21.222, 18.874, 15.77 ,
       20.998, 20.501, 19.667, 19.825,  8.719, 21.507, 19.098, 25.124,
       18.828,  8.372, 45.445, 14.745, 24.816, 23.757, 14.826, 23.753,
       14.589, 14.39 , 21.299, 13.605, 19.076, 21.211, 20.396, 23.303,
       29.038, 20.472, 14.43 , 15.666, 34.595, 19.29 , 21.034, 24.145,
       19.287, 30.385, 44.731, 19.301, 22.255, 13.502, 15.287, 24.513,
       18.793, 29.132, 21.117, 34.029, 16.578, 26.76 , 45.247, 22.038,
       15.556, 32.422, 22.502, 20.715, 25.472, 33.772, 28.331, 18.836,
       27.413, 17.726, 13.997, 23.024, 28.746, 15.458, 20.804, 28.31 ,
       10.438, 21.051, 21.699,  6.863, 20.197, 45.811, 11.373, 13.039,
       21.403, 12.788, 19.489,  9.086, 20.126, 26.872, 15.524, 23.293,
       23.664, 18.062, 21.456,  7.855, 19.535, 18.84 , 22.496, 19.94 ,
       38.751, 12.545, 12.318, 13.194, 20.622, 23.588])

In [13]:
# REGRESSION MODELS:
# 1.R SQUARED
# 2.MEAN ABSOLUTE ERROR(MAE)
# 3.MEAN SQUARED ERROR(MSE)

In [14]:
# 1.R SQUARED
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred))

0.8799258238349906


In [15]:
RFR.score(x_test,y_test)

0.8799258238349906

In [16]:
# 2.MEAN ABSOLUTE ERROR
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(y_test,y_pred))

2.1102254901960786


In [17]:
df=pd.DataFrame(data={'ACTUAL VALUE':y_test,'PREDICTED VALUE':y_pred})
df['DIFFERENCE']=df['ACTUAL VALUE']-df['PREDICTED VALUE']
df

ACTUAL VALUE  PREDICTED VALUE  DIFFERENCE
173          23.6           22.501       1.099
274          32.4           30.298       2.102
491          13.6           17.008      -3.408
72           22.8           23.048      -0.248
452          16.1           17.037      -0.937
..            ...              ...         ...
412          17.9           12.545       5.355
436           9.6           12.318      -2.718
411          17.2           13.194       4.006
86           22.5           20.622       1.878
75           21.4           23.588      -2.188

[102 rows x 3 columns]

In [18]:
# MEAN SQUARED ERROR
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test,y_pred))

8.805493598039215


In [19]:
# CROSS VAL SCORE
# THE SCORING PARAMETER:HIGHER RETURN VALUES ARE BETTER THAN LOWER VALUES 
from sklearn.model_selection import cross_val_score

In [20]:
# SCORING=NONE
np.random.seed(42)
np.mean(cross_val_score(RFR,x,y,cv=5,scoring=None))

0.6243870737930857

In [21]:
np.random.seed(42)
cross_val_score(RFR,x,y,cv=5,scoring=None)

array([0.77231143, 0.86035935, 0.74664002, 0.47632078, 0.26630379])

In [22]:
# SCORING=R SQUARED
np.random.seed(42)
cross_val_score(RFR,x,y,cv=5,scoring='r2')

array([0.77231143, 0.86035935, 0.74664002, 0.47632078, 0.26630379])

In [23]:
np.random.seed(42)
np.mean(cross_val_score(RFR,x,y,cv=5,scoring='r2'))

0.6243870737930857

In [24]:
# SCORING=MEAN ABSOLUTE ERROR(MAE)
np.random.seed(42)
cross_val_score(RFR,x,y,cv=5,scoring='neg_mean_absolute_error')

array([-2.11419608, -2.58716832, -3.33976238, -3.78563366, -3.32941584])

In [25]:
np.random.seed(42)
np.mean(cross_val_score(RFR,x,y,cv=5,scoring='neg_mean_absolute_error'))

-3.0312352552902335

In [26]:
# SCORING=MEAN SQUARE ERROR(MSE)
np.random.seed(42)
cross_val_score(RFR,x,y,cv=5,scoring='neg_mean_squared_error')

array([ -7.86326927, -12.71243178, -20.29089194, -45.93287403,
       -19.50774726])

In [27]:
np.random.seed(42)
np.mean(cross_val_score(RFR,x,y,cv=5,scoring='neg_mean_squared_error'))

-21.261442856882137

In [28]:
# REGRESSION EVALUATION FUNCTIONS
print(f'R-Suared:{r2_score(y_test,y_pred)}')
print(f'MAE:{mean_absolute_error(y_test,y_pred)}')
print(f'MSE:{mean_squared_error(y_test,y_pred)}')

R-Suared:0.8799258238349906
MAE:2.1102254901960786
MSE:8.805493598039215
