In [1]:
# X=FEATURES,FEATURE VARIABLES,DATAS
# y=LABELS,TARGETS
# IN REGRESSION SCORE() IS R SQUARED(DETERMINATION OF COEEFICIENT) WHERE AS IN CLASSIFICATION IT IS THE MEAN ACCURACY

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
Data=pd.read_csv('Heart_Disease.csv')

In [4]:
Data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [5]:
x=Data.drop('target',axis=1)
y=Data['target']

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [7]:
from sklearn.ensemble import RandomForestClassifier

In [8]:
RFC=RandomForestClassifier(n_estimators=100)

In [9]:
RFC.fit(x_train,y_train)

RandomForestClassifier()

In [10]:
y_pred=RFC.predict(x_test)
y_pred

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [11]:
np.array(y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [12]:
np.mean(y_pred==y_test)

0.8524590163934426

In [13]:
RFC.score(x_test,y_test)

0.8524590163934426

In [14]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.8524590163934426


In [15]:
RFC.predict(x_test[:5])

array([0, 1, 1, 0, 1], dtype=int64)

In [16]:
# PREDICT PROBA:INSTEAD OF RETURNING LABEL AS PREDICT() IT RETURNS THE PROBABILITY OF THAT LABEL BEING TRUE
RFC.predict_proba(x_test[:5])

array([[0.93, 0.07],
       [0.48, 0.52],
       [0.44, 0.56],
       [0.88, 0.12],
       [0.2 , 0.8 ]])